### ISSUE TITLE
Document the Package

### ISSUE THREAD

**Issue by andyDoucette** [dourouc05/CombinatorialBandits.jl#12]
Thank you for building this.  I'm afraid there isn't enough documentation though for anyone to know what to do.  There are policies, instances, solvers, and none of them have documentation to specify which one(s) should be used in which circumstances.  I'm sure what you've built is amazing, but without the documentation no one else can really use.

**Comment by dourouc05** [comment]
I have added quite a bit of docs to this package. You might be interested in the high-level description in https://github.com/dourouc05/CombinatorialBandits.jl/blob/master/docs/why.md.
